docs(apps/docs): add favicon and social image
sannajammeh/trpc-swr pull request #45
Opened 2023-05-16 02:24 UTC by r3nanp

2023-05-16 03:10 UTC, sannajammeh commented
Great stuff! Thanks for the PR. I see we need the open graph data for all pages, so removing the of check on the asPath would be preferred here. Set the title when asPath is not `/` to whatever you see fit, and otherwise leave it as it is. The rest of the openGraph is needed on all routes.

2023-05-16 13:44 UTC, sannajammeh requested changes
[apps/docs/theme.config.tsx](https://github.com/sannajammeh/trpc-swr/pull/45/files#diff-3a56172e097b6bd1ba518b93cd20c5af7f3a731ab8683c6f8b8e84044b695ad3)

2023-05-16 13:44 UTC, sannajammeh commented on apps/docs/theme.config.tsx
Remove line 9 `if (asPath !== "/") {`

And replace line 23 `titleTemplate: "%s - tRPC SWR",` with `titleTemplate: asPath !== "/" ? "tRPC SWR" : "%s - tRPC SWR",`

2023-05-16 23:12 UTC, r3nanp commented on apps/docs/theme.config.tsx
Thanks for the heads up!

2023-05-16 23:14 UTC, sannajammeh approved these changes
Great stuff!

2023-05-17 23:36 UTC, r3nanp commented
A small problem in this GitHub actions job:
https://github.com/sannajammeh/trpc-swr/actions/runs/4997532792/jobs/8952024363?pr=45

2023-05-18 13:05 UTC, merged